### ISSUE TITLE
View Dataspace Catalog (Offers Shared with Me)

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#10]
Feature #3 

## Description

As a dataspace participant I want to look at all the data assets that other participants offer to share with me.

The connector's web UI offers a page to display all data offerings, which can be obtained through the connector's REST API. 
The catalog crawler collects as `ContractOffer`s from all participants by obtaining the participant list from the `RegistrationService`. 

## Acceptance Criteria
- [x] Web UI lists all offerings. Advanced search/filtering is out of scope (will be in #87)
- [x] Offerings include data assets other participants offer to share with me.
- [x] Documentation on how to view offerings through the UI is available
- [x] Offerings can be viewed based on step by step instructions without having deep technical expertise

## Tasks

As the UI side is already implemented in the webapp, only a bug fix and documentation are outstanding.

- [ ]  <strike>Fix empty columns in UI (timestamp, Protocol)</strike>
- [x]  Documentation on how to view dataspace catalog through the UI is available

**Comment by algattik** [comment]
@zeier I think this would be best spread in multiple stories per feature.
- ("Web UI lists all offerings and allows sorting, filtering and grouping (by name, asset owner, etc.)")
- assets I share with others vs assets shared with me

we should start with 1 story with basic list of offerings, and only assets shared with me

**Comment by algattik** [comment]
> @zeier I think this would be best spread in multiple stories per feature.

Done, created #86, #87

**Comment by cpeeyush** [comment]
- Offerings include data assets other participants offer to share with me. -> Only asset ID is available now on UI and this ID can be anything e.g. UUID.
