### ISSUE TITLE
Policy: simple setup

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#100]
Feature #3 
After #19 
Before #21 

## Description

In #57 #97 we spiked the creation of a simple rule-based policy.
- Caller must present credentials on which policies are evaluated. Until #64 is implemented, we can use the `iam-mock` extensions to have caller present mock credentials that callees trust.
- Policies must be defined with specific IDS Policy Rules (permissions, prohibitions, or duties) and use in contract definition objects.
- Implementations of the rules must exist in EDC runtime. The `ids-policy` module provides a few simple rule implementations, otherwise custom ones can be packaged.

For the simplest demonstrative setup, we want to:
- expose two assets, and have a simple region-based rule on one asset.
- Have two consumer connectors with two different regions.
- One of the assets should be offered to both consumers (and appear in their catalog), the other only to one consumer.

## Implementation details (spike results)

The `ids-policy` module provides the ABS_SPATIAL_POSITION function that can be used to build policies that depend on the region of the caller.

A custom extension can be created to define the required type and bind the function to a scope:

```java
         ruleBindingRegistry.bind("USE", ContractDefinitionService.NEGOTIATION_SCOPE);
         ruleBindingRegistry.bind(ABS_SPATIAL_POSITION, ContractDefinitionService.NEGOTIATION_SCOPE);
```

This can be used in a policy such as this to limit contract negotiation to callers from a specific region:

```
{
    "uid": "956e172f-2de1-4501-8881-057a57fd0e69",
    "permissions": [
        {
            "edctype": "dataspaceconnector:permission",
            "uid": null,
            "target": null,
            "action": {
                "type": "USE",
                "includedIn": null,
                "constraint": null
            },
            "assignee": null,
            "assigner": null,
            "constraints": [
                {
                    "edctype": "AtomicConstraint",
                    "leftExpression": {
                        "edctype": "dataspaceconnector:literalexpression",
                        "value": "ids:absoluteSpatialPosition"
                    },
                    "rightExpression": {
                        "edctype": "dataspaceconnector:literalexpression",
                        "value": "eu"
                    },
                    "operator": "EQ"
                }
            ],
            "duties": []
        }
    ],
    "prohibitions": [],
    "obligations": [],
    "extensibleProperties": {},
    "inheritsFrom": null,
    "assigner": null,
    "assignee": null,
    "target": null,
    "@type": {
        "@policytype": "set"
    }
}
```

## Acceptance criteria
- [ ] Three connectors are deployed in CD, two with `region=eu` and one with `region=us`. The region is visible in the connector web API URL.
- [ ] The connector with `region=us` sees one asset from each of the other connectors. The connector with `region=eu` sees two assets from each of the other connectors. 

## Tasks
- [ ] Change the CD setup to deploy three participants, with two participants in `region=eu` and one in `region=us`.
- [ ] Use the `edc.mock.region` in `IamMockExtension` to have each participant present a mock authentication token containing its region.
- [ ] Create a custom extension to bind `USE` and `ABS_SPATIAL_POSITION` as in spike code.
- [ ] Extend the Postman seed data to retain the existing "permissive" policy on one asset, and add a second asset with a policy that restricts it to `region=eu`.
- [ ] A sample verifiable credential (region=eu) is used to restrict access for some participants not in the eu region
- [ ] Adapt CatalogTest to run against `region=us` client, and verify that the first asset (not restricted by region) is present, and the second asset (restricted by region) is not present in the catalog
