### ISSUE TITLE
Asset Contract Negotiation

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#11]
Feature #3 
Depends on agera-edc/EDCDataDashboard#11

## Description
As a dataspace participant I want to initiate a contract negotiation with another participant to gain access to a particular asset.

The web UI lists all ContractOffers that "our" connector has access to, and shows a button to trigger the negotiation for a particular asset. This calls the DataManagement API of the connector at POST /contractnegotiations.

Then the negotiation process happens, and once that is done, the respective entry in the ContractNegotiationStore should have a ContractAgreement attached to it.

Note: this should show all offers from all participants

## Acceptance Criteria
- [x] List with offer is displayed on web UI (#10)
- [x] Contract negotiation can be performed
- [x] Documentation on how to perform a contract negotiation through the UI is available
- [x]  Contract negotiations can be performed based on step by step instructions without having deep technical expertise

## Tasks

As the UI side is already implemented in the webapp, only documentation is outstanding.

- [x]  Documentation on how to perform a contract negotiation through the UI is available
