### ISSUE TITLE
Registration Service - Participant onboarding - Applies a simple policy on participant's verifiable credentials (without checking their signers)

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#11]
Feature agera-edc/MinimumViableDataspaceFork#24
After agera-edc/MinimumViableDataspaceFork#48 agera-edc/MinimumViableDataspaceFork#41 agera-edc/MinimumViableDataspaceFork#12 #225 

## Description

During participant onboarding registration service should apply policies on participant verifiable credentials in order to validate if onboarding participant can be part of current dataspace or not.

## Acceptance Criteria

- [x] Update ADR about enrollment endpoint if required. (#209)
- [x] Registration service apply membership policy - participant must be a GAIA-X member.
- [x] Test coverage.

## Tasks

- [x] Update ADR
- [x] Registration service applies policies during onboarding. Participant is a GAIA-X member. (❓ how to verify GAIA-X membership)
- [x] Policy verification is extensible to one or more policies.
- [x] Test coverage.
