### ISSUE TITLE
Spike: - Decentralized Identity - WebDiD

### ISSUE THREAD

**Issue by chrislomonico** [agera-edc/MinimumViableDataspace#113]
## Related 
Feature agera-edc/MinimumViableDataspaceFork#116 

## Description
Investigate components and interactions required for Web DID.

##  Acceptance Criteria
- [x] ADR on Web DID implementation
- [x] Follow-up stories for Web DID implementation are created

## Tasks

- [x] Analyze Web DID flow in edc-showcase
- [x] Write ADR
- [x] Create follow-up stories
- [x] Present results to the team

## Notes:

2022.04.06 - Marc/Chris interested in working on this
