### ISSUE TITLE
CD initial pipeline

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#117]
Scope is summarised below, see document for more details.

Feature agera-edc/MinimumViableDataspaceFork#119 
After agera-edc/MinimumViableDataspaceFork#118 

CD: initial scope
-	Build and push to ACR
-	Deploy dataspace participant job matrix
-	Job for destroying infrastructure

### Tasks

- [x] Develop CI/ CD pipeline with build job, deploy job matrix, and destroy job 
- [x] Document CD pipeline

### Acceptance criteria

- [x] On push to any branch or on PR, 3 EDC deployments (with AKV, ACI, Storage) are performed and then destroyed
- [x] CD job tests that EDC application is healthy
- [x] Destroy job destroys all infra even on partial deployment/health test failures
- [x] Branches do not interfere with each other: resources can be deployed in parallel (e.g. using GitHub run_id in resource names), if not possible then concurrency is limited
