### ISSUE TITLE
Registration Service - Participant onboarding - Obtains participant verifiable credentials from caller participant hub (still applying no policy)

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#12]
Feature agera-edc/MinimumViableDataspaceFork#24
After agera-edc/MinimumViableDataspaceFork#48 agera-edc/MinimumViableDataspaceFork#41 agera-edc/MinimumViableDataspaceFork#13 

## Description

During participant onboarding registration service must be able to obtain participant verifiable credentials. 

Out of scope:

Applying any policy on obtained verifiable credentials.

## Acceptance Criteria

- [x] Update ADR about enrollment endpoint if required. (#209)
- [x] Participant identity hub contains verifiable credentials for onboarding,
- [x] Registration service able to obtain verifiable credentials from participant identity hub during onboarding. (apply no policy)
- [x] Test coverage.

## Tasks

Same as acceptance criteria.
