### ISSUE TITLE
Lookup Existing Contracts

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#13]
Feature #3
Requires https://github.com/agera-edc/EDCDataDashboard/issues/6

## Description

As a dataspace participant I want to be able to see all `ContractAgreements` that I have already negotiated.

Every connector offers a list of ContractAgreements through an HTTP endpoint:
`GET /contractagreements`

Story for frontend work: https://github.com/agera-edc/EDCDataDashboard/issues/6

## Acceptance Criteria
- [x] Connector UI (#18) lists all contract agreements including its details (see https://github.com/agera-edc/EDCDataDashboard/issues/6)
- [x] Documentation on how to lookup existing contracts through the UI and REST API is available
- [x] Existing contracts can be looked up based on step by step instructions without having deep technical expertise

## Tasks

As the UI side is covered in https://github.com/agera-edc/EDCDataDashboard/issues/6, only documentation is outstanding here.

- [x]  Documentation on how to perform a contract negotiation through the UI is available

**Comment by algattik** [comment]
Currently the webapp shows the option to perform a transfer only if the contract was negotiated immediately in the same page. The solution could be to keep this experience in the Dataspace Catalog, and make the UI not offer to negotiate again contracts that are already in place.

However that would make invisible contracts that were previously agreed but are not offered anymore.

**Comment by zeier** [comment]
Proposal is to have one view per step (i.e. scenario).
