### ISSUE TITLE
Registration Service - Participant onboarding - Issues a dataspace membership VC and pushes it to the corresponding identity hub

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#13]
Feature agera-edc/MinimumViableDataspaceFork#24
After agera-edc/MinimumViableDataspaceFork#48 https://github.com/agera-edc/IdentityHub/issues/21 agera-edc/MinimumViableDataspaceFork#14  agera-edc/MinimumViableDataspace#151 

## Description

During participant onboarding registration service should issue a dataspace membership verifiable credential (VC) and store it in participant identity hub.

## Acceptance Criteria

- [x] Update ADR about enrollment endpoint if required. (#209)
- [x] Registration service able to issue a dataspace membership VC.
- [x] Registration service able to store VC in participant identity hub.
- [x] Test coverage.

## Tasks

- [x] ADR update
- [x] Registration service creates dataspace membership VC.
- [x] Registration service stores membership information in its registry. At the very least, this includes Participant's DID URL
- [x] Store membership VC to participant identity hub. (No auth for identity hub)
- [x] Test coverage.
