### ISSUE TITLE
EDC Data Dashboard Documentation Wrap-up

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#133]
Feature #3 

## Description

The docs pages for the EDC Data Dashboard are currently located under `docs/developer`. Since there will be docs for multiple topics under this folder, we want to move all the docs that describe basic scenarios with the data dashboard to a dedicated folder and provide an overview page in the `docs/developer` folder that as an entry point.

## Acceptance Criteria

- [ ] Overview page for basic scenarios covered in #3 is available in the `docs/developer` folder
- [ ] Further docs are located in a dedicated folder

## Tasks

- [ ] Move all documentation pages related to #3 to `docs/developer/edc-data-dashboard`
- [ ] Create overview page in `docs/developer` for the basic scenarios, describe that they can be covered with the EDC Data Dashboard and link to the corresponding `edc-data-dashboard` folder
- [ ] Update links if required
