### ISSUE TITLE
Registration Service - Participant onboarding- Verifies participant JWS

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#14]
Feature agera-edc/MinimumViableDataspaceFork#24

After https://github.com/agera-edc/DataSpaceConnector/issues/311
After https://github.com/agera-edc/DataSpaceConnector/issues/269

## Description

When a participant interacts with Registration service it should send a signed JWS to registry service and registry service should verify participant JWS. In order to do so registry service should first get participant DID document from DID url defined in JWS and use public key from this DID to verify signed JWS.

spec : https://github.com/Metaform/mvd/blob/main/registration-service/registration-service-tech-spec.md

Note that a fix for https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1176 is being developed, in order to include audience check

## Acceptance Criteria

- [x] Update ADR about enrollment endpoint if required. (#209)
- [x] Participant should send a signed JWS when interacting with registration service.
- [x] Registration service verifies participant's JWS using it's participant public key.
- [x] Test coverage.
- [x] Uses updated EDC code after fixing https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1176

## Tasks

- [x] Update ADR.
- [x] Participant create signed JWS. It contains DID document url of participant.
- [x] Participant send signed JWS to registration service during any interaction.
- [x] Registration service able to verify participant's JWS.
- [x] Test coverage

**Comment by algattik** [comment]
Requires two EDC upstream fixes

**Comment by cpeeyush** [comment]
Upstream PR for registration service JWS Verification and client cli modifications 

https://github.com/eclipse-dataspaceconnector/RegistrationService/pull/11

**Comment by cpeeyush** [comment]
Upstream PR merged.
