### ISSUE TITLE
Lookup Past Transfers

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#14]
Feature #3

## Description

As a dataspace participant I want to be able to see all past `Transfers` that I have already performed.

Every connector offers its transfer history through an HTTP endpoint:
`GET /transferprocess`

## Acceptance Criteria

- [x] Connector UI (#18) lists all previous transfer processes
- [x] Documentation on how to lookup past transfers through the UI is available
- [x] Past transfers can be viewed based on step by step instructions without having deep technical expertise

Out of scope: Capabilities in addition to the current state of the UI in terms of filtering, pagination and sorting.

## Tasks

As the UI side is already implemented in the webapp, only documentation is outstanding.

- [x]  Documentation on how to view past transfers through the UI is available

**Comment by cpeeyush** [comment]
Filtering, Pagination, Sorting is out of scope?

**Comment by zeier** [comment]
Removed doc for the rest API and UI capabilities for filtering, pagination and sorting.

The corresponding information (e.g. Timestamp which is currently missing) should be available and correct though.
