### ISSUE TITLE
Use different assetId for each company asset in MVD

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#150]
Upstream https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/issues/7

## Description

For system-tests we upload assets for each participant with MVD.postman_collection.json.
All assets have the same assetId for individual participants.
In a dataspace we should not have assets with the same assetId.

A corresponding [upstream bug](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/issues/7) is available.

To aspects are required to fix this bug:

-  We need to deduplicate the assetId in MVD, as duplicate IDs can be confusing
- EDC and the webapp should properly manage ID collisions. In the webapp we should show the asset originator next to the asset Id, and the EDC crawler needs to be fixed to properly handle ID collisions

## Acceptance Criteria

- [ ] [Upstream bug](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/issues/7) is fixed
- [ ] Participants use different IDs for their assets
- [ ] The webapp shows the asset originator next to the asset Id (to be able to distinguish between assets with the same ID)
- [ ] The EDC crawler is capable to properly handle ID collisions (assets with the same ID from different participants)

## Tasks

- [ ] Investigate root cause
- [ ] Split story into two if multiple areas are affected

**Comment by algattik** [comment]
@zeier I think the fix should be a different one, participants cannot coordinate among themselves to avoid assetId duplication.

Rather, EDC and the webapp should properly manage ID collisions. In the webapp we should show the asset originator next to the asset Id.

**Comment by zeier** [comment]
@algattik, agreed that the same asset ID may be used by different participants, and that ID collisions should be handled properly.

At the same time, having the same asset ID for multiple assets in a dataspace can still be confusing, so I think the fix should include both points.

**Comment by algattik** [comment]
@zeier could we split this into two, since it is two things in two different repos?

**Comment by zeier** [comment]
Yes that's a good idea, let's discuss during the backlog refinement team Q&A session.

**Comment by marcgs** [comment]
Fixed upstream
