### ISSUE TITLE
GAIA-X Authority - DID

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#151]
Feature #78 
After #18 

## Description

MVD GAIA-X authority should have DID document related to it.
Similar story for the reference: https://github.com/agera-edc/MinimumViableDataspace/issues/44

## Acceptance Criteria

- [ ] Well-known DID endpoint for MVD GAIA-X authority deployed.
- [ ] DID document contains public key

## Tasks
- [ ] Deploy DID document for GAIA-X in github workflow
