### ISSUE TITLE
MVD Azure Monitor Integration

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#154]
##  Description

OpenTelemetry-based observability is required for the MVD as it is currently in place for the EDC, to allow developers to investigate issues more effectively. This includes distributed tracing across applications, logging and metrics. Data shall be collected in Azure Monitor.

At this time we will deploy a single Azure Monitor instance for all participants.

Changes required: OpenTelemetry agent in container runtime, CD code to provision Azure Monitor and inject key into EDC runtime.

## Acceptance Criteria
- [ ] MVD distributed traces, logs and metrics for all participants are visible in Azure Monitor
- [ ] Documentation explaining setup, highlighting in a real dataspace participants might have separate monitoring systems

## Tasks
- [ ] Provision Azure App Insights instance for MVD
- [ ] Set up environmental variables in EDC container for App Insights integration
- [ ] Documentation as described above
