### ISSUE TITLE
IdentityHub - Command line client 

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#155]
Feature [#71](https://github.com/agera-edc/MinimumViableDataspace/issues/71)

## Description

A command line application needs to be created which can act as Identity Hub client and this application is responsible for populating the Verifiable Credentials into participant's Identity Hub. This command line application internally uses IdentityHub API. A participant can be onboarded without the need of deploying it first.

MVD deployment pipeline should use this command line client in order to populate the Verifiable Credentials .

## Acceptance Criteria

- [ ] CLI is documented
- [ ] Identity Hub command line client available to onboard participant. 
- [ ] Identity Hub command line client is able to push VCs to Identity Hub for onboarding
- [ ] IH CLI is used in MVD deployment workflow in the participants onboarding process 
- [ ] Testing coverage.

## Tasks

- [ ] Implement Identity Hub CLI
- [ ] Update docs and including local development instructions
- [ ] Use Identity Hub CLI in MVD deployment workflow to push VCs signed by GAIA-X Authority to participants Identity Hub during the onboarding
