### ISSUE TITLE
Participant Deployment Pipeline

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#158]
Feature #91

## Description 
We need to have a pipeline to deploy the azure resources of a new participant manually.

## Acceptance Criteria

- [ ] The Azure resources for a new participant can be deployed, the participant is not onboarded yet
- [ ] The workflow deploying a new participant can be triggered manually by clicking a button

## Tasks

- [ ] Create a workflow to deploy a new participant
- [ ] Update the documentation

**Comment by zeier** [comment]
Put on hold since capacity until end of sprint 13 is projected to be insufficient to cover this feature.
Can be taken up as the next priority feature if capacity is available.
