### ISSUE TITLE
Participant Destroy Pipeline

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#159]
Feature #91

## Description 
Participant resources that have been created via the [Deploy Participant workflow](https://github.com/agera-edc/MinimumViableDataspace/issues/158) should be destroyed easily. This story is about creating a pipeline to easily destroy a participant.

## Acceptance Criteria
- [ ] The workflow deploying a new participant can be triggered manually by specifying the participant name and clicking a button

## Tasks

- [ ] Create the workflow to destroy a participant resources
- [ ] Update the documentation

**Comment by zeier** [comment]
Put on hold since capacity until end of sprint 13 is projected to be insufficient to cover this feature.
Can be taken up as the next priority feature if capacity is available.
