### ISSUE TITLE
Manual Participant Onboarding

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#160]
Feature #91

## Description 
Somebody playing with the MVD should be able to [create a participant](https://github.com/agera-edc/MinimumViableDataspace/issues/158) and onboard the participant in the MVD dataspace.
This story is about providing the instructions to onboard a new participant.

## Acceptance Criteria
- [ ] A participant can be onboarded by following the provided instructions.

## Tasks
- [ ] Create an ADR with the onboarding concept
- [ ] Add instructions to use the CLI (checkout repo and build the CLI or download it)
- [ ] Add instructions to onboard a participant

**Comment by zeier** [comment]
Put on hold since capacity until end of sprint 13 is projected to be insufficient to cover this feature.
Can be taken up as the next priority feature if capacity is available.
