### ISSUE TITLE
Deployment Pipeline Refactoring

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#161]
Feature #91

## Description
We want to have a [workflow to create a new participant manually](https://github.com/agera-edc/MinimumViableDataspace/issues/158). 
If we don't refactor the MVD deploy workflow, adding a "Deploy participant" workflow would imply duplication of the deploy workflow. To avoid that, we could refactor the workflows.

The Deploy-Participant job can be moved to a workflow. This workflow would be called several times from cd workflow to deploy the 3 participants and could also be triggered manually.
The same would be needed for the Destroy workflow.

The goal of this story would be to figure out if this refactor is possible, and implement it if it is.

## Acceptance Criteria
- [ ] A "Deploy participant" workflow is used in cd and can also be triggered manually
- [ ] A new "Destroy participant" workflow is used in cd and can also be triggered manually
- [ ] System tests are still running

## Tasks
- [ ] Figure out if it is possible to reuse output from a workflow from a caller workflow
- [ ] Use Deploy-Participant and Destroy-Participant workflows in cd instead of jobs
- [ ] Make sure the Deploy-Participant can be triggered manually
- [ ] Add a verify workflow that reuses Deploy-Participant workflow outputs

**Comment by zeier** [comment]
Put on hold since capacity until end of sprint 13 is projected to be insufficient to cover this feature.
Can be taken up as the next priority feature if capacity is available.
