### ISSUE TITLE
Upgrade MVD with the latest EDC version

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#162]
## Description

Upgrade MVD repository with the latest version of EDC.

## Acceptance Criteria

- [ ] MVD repository is upgraded to the latest version of EDC

## Tasks

- [ ] Upgrade MVD repo with the latest EDC commit hash
- [ ] Fix all breaking changes
