### ISSUE TITLE
EDCDataDashboard CD setup

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#163]
Feature #147
After #161

## Description
Set up CD for the new EDCDataDashboard repository in the `eclipse-dataspaceconnector` org.
Jim and Paul will take care of this setup, but this story is a placeholder to keep track of the state, and in case support from team members is needed.

## Acceptance criteria
- [ ] An Azure subscription for CD is setup
- [ ] Actions Github secrets needed for CD are configured in the new github repository

## Tasks
- [ ] Initiate the work & coordinate with Jim & Paul
- [ ] Verify that CI/CD works
- [ ] Support Jim & Paul if needed
- [ ] Setup CD for forked repository

**Comment by algattik** [comment]
Closed in favour of https://github.com/agera-edc/EDCDataDashboard/issues/39
