### ISSUE TITLE
Identity Hub - Repository Setup

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#164]
Feature #122 

## Description

A new repository for the Identity Hub needs to be setup in the eclipse-dataspaceconnector organization.

## Acceptance Criteria

- [x] Repository for Identity Hub is available in the eclipse-dataspaceconnector organization
- [x] All Agera team members have access to push into the repo
- [x] Issues in the agera-edc GitHub org related to the Identity Hub are moved to the downstream Identity Hub repository

## Tasks
- [x] IdentityHub repository is created in eclipse org
- [x] IdentityHub downstream fork is created in agera org
- [x] Set up License terms in the README
- [x] Double check that the correct protections rules are in place for the `main` branch
- [x] Document process to contribute in the README (Code of conduct, sign the ECA etc.)
~- [ ] Document internal agera process to contribute to the IdentityHub in our wiki~ obsolete: already documented
- [x] Set license to Apache 2.0
- [x] IdentityHub stories are moved to fork in agera org

**Comment by chrislomonico** [comment]
empty upstream [repository](https://github.com/eclipse-dataspaceconnector/IdentityHub) has been created

**Comment by chrislomonico** [comment]
- Downstream [repo ](https://github.com/agera-edc/IdentityHubFork)created
- All Issues have been migrated (there were no existing issues to migrate)

**Comment by chrislomonico** [comment]
- PR completed for code migration
- Renamed old repo to `IdentityHubOld`
