### ISSUE TITLE
Dependency Management Concept (ADR)

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#164]
Feature: #30 

## Description

Create an ADR in MVD repository that logs the decision about the dependencies sharing across MVD repositories (MinimumViableDataspace, Registration Service, IdentityHub, etc.).
Currently the services are using locally published dependencies. It's difficult set up especially for local development. 
This story aims to define the dependency management concept that would include:
- Versioning of the published artifacts.
- Explanation how services are dependent on each other and which versions they are using.
- Proposal for the local development routine for changes across multiple repositories.

Useful link to the repo split spike (contains spike for the local development setup, versioning for multirepo etc):
- [Repo split ADR](https://github.com/agera-edc/DataSpaceConnector/blob/spike/63-repo-split/docs/developer/decision-records/2022-03-01-repo-split/README.md)

Additional information on how to add EDC Maven dependencies and regarding release management:
- [Add maven dependencies](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/README.md#add-maven-dependencies)
- [Releases](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/developer/releases.md)

## Acceptance criteria

- [ ] Dependency Management Concept is documented in ADR
- [ ] Stories #165 #166  and #167 are updated with details if needed
- [ ] New stories are created if needed

## Tasks

- [ ] Design the Dependency Management Concept
- [ ] ADR
- [ ] Update or create stories of needed

**Comment by zeier** [comment]
Put on hold, as it is projected to be too much scope for the team until end of August.
#36 and #157 have higher priority.
This item can be taken up again if there is capacity.
