### ISSUE TITLE
Fix MVD Asset Publishing

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#167]
## Description

Publishing assets into a dataspace using a contract definition seems to be buggy:
- Sometimes published assets are not visible in other connectors
- Sometimes previously published assets that were visible in the catalog disappear

## Acceptance Criteria
- [ ] Asset publishing within the MVD is tested
- [ ] Fix low hanging fruits
- [ ] Open separate stories for larger bugs

## Tasks
