### ISSUE TITLE
CPR OneWeek demo

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#168]
## Description
Prepare the demo showing the work done during OneWeek: the integration of Dataverse with EDC.
Show publishing of an asset + transfer from Dataverse to blob storage.

## Acceptance criteria
- [ ] Recording is ready
- [ ] Demo shows asset publication and transfer from Dataverse to blob

## Tasks
- [ ] Integrate together the publishing of asset and the transfer
  - [ ] Add the Dataverse URL in asset properties & and uses this property for the data transfer.
- [ ] Get the app token programmatically instead of hardcoding it
- [ ] Record the demo
