### ISSUE TITLE
GAIA-X Authority VCs - Infrastructure Implementation

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#17]
feature #78   
after #18  and https://github.com/agera-edc/MinimumViableDataspace/issues/151

## Description
Implementation story according to outcome of #18  

## Acceptance Criteria
- [x] All verifiable credentials can be validated against the public key of the issuer's DID document
- [x] GAIA-X membership Verifiable Credential can be issued by an external authority trusted by dataspace participants and can be verified by the dataspace authority
- [x] MVD Membership verifiable credentials signed by the dataspace authority can be issued and verified by any dataspace participant
- [x] Documentation on how certificate infrastructure is handled for the MVD

## Tasks
- [x] Generate private and public keys for GAIA-X in the CD workflow.
- [x] The GAIA-X private key is made available to download as Github artifact so that it can be used in the participant deployment workflow to generate GAIA-X membership Verifiable Credentials. 
- [x] Populate the GAIA-X VCs to participant's IdentityHub using the Identity Hub CLI
- [x] Add/update doc on how certificate infrastructure is handled for the MVD

**Comment by zeier** [comment]
Currently blocked by the missing IdentityHub implementation, requires IdentityHub CLI.
