### ISSUE TITLE
MVD - Test reports and code coverage

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#172]
## Description

MVD workflow executes Unit, Integration & System tests but reports are not published. This needs to be fixed so tests reports are available as github artifacts.

(Similar Pattern is followed in EDC https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/30198170ffa3fe3609ed6778953a1e963ac7703b/.github/actions/run-tests/action.yml#L14 and for gatling reports https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/30198170ffa3fe3609ed6778953a1e963ac7703b/.github/workflows/verify.yaml#L208, 
publishing to Codecov: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/30198170ffa3fe3609ed6778953a1e963ac7703b/.github/workflows/verify.yaml#L448)

## Acceptance Criteria

- [ ] Gatling reports are published.
- [ ] Unit Test reports are published with code coverage reports.
- [ ] Test coverage shows up in CodeCov reports

## Tasks

Same as acceptance criteria.

**Comment by algattik** [comment]
Draft PR from previous code at https://github.com/agera-edc/MinimumViableDataspace/pull/173
