### ISSUE TITLE
Registration service: Participant record should not contain service URLs

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#174]
Feature #24
After #14 (as the PR in preparation affects the Participant record structure)
Related to #19 

## Description

Participant record served by registration service should only contain a DID URL. Other service URLs should be resolved through DID document.

The `name` field could be removed as well (and potentially re-introduced later after we clearly define how to manage it - updates, collisions etc. - but if a name string is required, it should probably come from the DID as well)

## Acceptance criteria

- [x] In RegistrationService, The entities returned in the registration service "List participants" operation only contain a DID URL
- [x] In MVD, DID documents of participants contain IDS endpoint
- [x] In MVD, FederatedCacheNodeDirectory resolves participants' DID documents to fetch IDS endpoints

## Tasks

- [x] Update Registration Service to only contain DID of participant on registration.
- [x] List of Participants from Registration Service returns only DID per participant.
- [x] DID doc of each participant contain IDS url.
- [x] In MVD, FederatedCacheNodeDirectory resolves participants' DID documents to fetch IDS endpoints.
- [x] Test coverage - Registration Service and MVD.
