### ISSUE TITLE
Registration Service - Repository Setup

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#178]
Feature agera-edc/MinimumViableDataspace#177

Relates to [Identity Hub Repository Setup](https://github.com/agera-edc/MinimumViableDataspace/issues/164)

## Description

Setup repository for Registry service.

## Acceptance Criteria

- [x] Repository is available in the eclipse-dataspaceconnector organization
- [x] All Agera team members have access to push into the repo
- [x] Issues in the agera-edc GitHub org related to the Identity Hub are moved to the downstream Repository

## Tasks

- [x] Repository is created in eclipse org
- [x] Repository downstream fork is created in agera org
- [x] Set up License terms in the README
- [x] Double check that the correct protections rules are in place for the `main` branch
- [x] Document process to contribute in the README (Code of conduct, sign the ECA etc.)
~- [ ] Document internal agera process to contribute in our wiki~ obsolete: already documented
- [x] Set license to Apache 2.0
- [x] Stories are moved to fork in agera org

**Comment by chrislomonico** [comment]
upstream [repository ](https://github.com/eclipse-dataspaceconnector/RegistrationService)has been created

**Comment by chrislomonico** [comment]
- Downstream [repo ](https://github.com/agera-edc/RegistrationServiceFork/)created
- Issues migrated (there are no issues to migrate to new repo at this time)

**Comment by chrislomonico** [comment]
migration complete
