### ISSUE TITLE
Registration Service - Scaffolding + CI pipeline

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#179]
Feature agera-edc/MinimumViableDataspace#177
After agera-edc/MinimumViableDataspace#178 

## Description

Create Registry service web service with simple health endpoint. It should be based on EDC, a separate runtime can be created for it.  CI pipeline should build the registration service and run necessary tests to validate build.

This repo could be used as template: https://github.com/agera-edc/RegistrationService/tree/paul/initial

## Acceptance Criteria

- [ ] Registry service with health endpoint
- [ ] CI pipeline

## Tasks

- [ ] Create registry service runtime. (See for reference https://github.com/agera-edc/RegistrationService)
- [ ] Create CI pipeline to build, run tests. Workflow should also validate PRs and merged changes.
