### ISSUE TITLE
Public Keys Infrastructure ADR

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#18]
feature agera-edc/MinimumViableDataspaceFork#78 

## Description

Certificate infrastructure to enable signed Verifiable Credentials must be designed and documented in an ADR. Refer to the description in feature agera-edc/MinimumViableDataspaceFork#78 for more information on the requirements for the MVD.

## Acceptance Criteria
- [ ] ADR on certificate infrastructure for MVD is created
- [ ] ADR is reviewed by the team
- [ ] Further details are added to story agera-edc/MinimumViableDataspaceFork#17 according to ADR
- [ ] ~(stretch goal) ADR is reviewed by a security expert (Stefan var der Wiele)~

## Tasks 
- [x] Organize design session
- [x] Design a Certificate infrastructure to enable signed Verifiable Credentials
- [ ] Create ADR on Verifiable Credentials verification for MVD onboarding. 
  - [x] Participants can only be enrolled in the dataspace if they have a GAIA-X membership VC issued by a "GAIA-X Authority". 
  - [x] In CD, deploy a first component ("GAIA-X Authority") that has a private key and a DID document containing a public key. 
  - [x] The "GAIA-X Authority" private key will be used in the participant deployment workflow, to generate a GAIA-X membership credential and populate their identity hub. This will be done with a to-be-developed Identity Hub CLI (similar in design to Registration Service CLI). We will allow participants to download the CLI and the private key (e.g. GitHub artifact) to deploy additional participants. 
  - [x] The Registration Service will be configured at deployment time with the DID of the GAIA-X Authority to trust.
- [x] Create ADR on IDS CredentialsVerifier (refer to authorization subflow https://github.com/agera-edc/MinimumViableDataspace/pull/146)
- [ ] Update story #17  if needed
- [ ] ~(stretch goal) Contact  Stefan van der Wiele for a review of the ADR~

**Comment by zeier** [comment]
Discussed during the EDC get-together workshop June 28 that a review by Stefan van der Wiele is not required.
