### ISSUE TITLE
Registration Service - rest api endpoint to list participant from file share

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#181]
Feature agera-edc/MinimumViableDataspace#177
After agera-edc/MinimumViableDataspace#179 

## Description

Registry service needs to expose a rest api endpoint which can be used to get list of dataspace participant. For this task this list can be read from existing file share. A participant of dataspace should use this new endpoint to fetch list of all other participants and do not read existing shared file from storage. 

## Acceptance Criteria

- [x] Registry service list dataspace participants rest api endpoint is available.
- [ ] Participant do not use shared file to get list of other participant. Use this new endpoint.
- [x] Open API doc is generated/updated and validated during CI build.
- [ ] Test coverage wherever applicable.

## Tasks

- [x] Create endpoint to list dataspace participants.  OpenAPI doc also available for endpoint.
- [x] UTs/ITs for list participants endpoint. 
- [x] Generate registry service java client from OpenAPI doc.
- [ ] Update MVD participants/crawler extension to use new endpoint to get list of participant. 
- [ ] Update doc https://github.com/agera-edc/MinimumViableDataspace/tree/main/docs/developer/decision-records/2022-04-28-federated-catalog
