### ISSUE TITLE
Participant Self-Description

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#186]
Feature agera-edc/MinimumViableDataspace#36
After agera-edc/IdentityHub#11
After agera-edc/IdentityHub#21

## Description

Provide a self-description document for each dataspace participant via IdentityHub (see agera-edc/MinimumViableDataspace#36 and agera-edc/IdentityHub#11). 

The content of the self-description document is currently not consumed by any use cases and thus can be defined based on the examples that were created for the last [Gaia-X Hackathon](#37).

## Acceptance Criteria

- [ ]  Self-description for each dataspace participant can be retrieved from the dataspace participant's IdentityHub

## Tasks

- [ ] Set up self-description documents for dataspace participants
- [ ] Expose self-description document via IdentityHub
