### ISSUE TITLE
ADR for Local Machine MVD

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#189]
Feature #157 
After #188

## Description

An ADR to document the design decision for the local machine MVD based on #188 is required.

## Acceptance Criteria

- [ ] ADR for the local machine MVD is available in the MVD repository
- [ ] Story #191 is updated with additional insights on how the local machine MVD runner will be implemented

## Tasks

- [ ] Add ADR for local machine MVD
- [ ] Update Story #191

**Comment by zeier** [comment]
Closed as not planned, because the only remaining piece of work is to integrate the DataDashboard and update the documentation, which does not require an ADR.
