### ISSUE TITLE
Azure Deployment with Terraform

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#19]
Feature #1 
After #2 
Related to #65

## Description

Stakeholders can perform an initial deployment of the MVD components to set up their MVD instance with a predefined set of three dataspace participants.

## Acceptance Criteria

- [x] MVD components can be deployed to a custom Azure subscription
- [ ] The three default dataspace participants (i.e. their connectors) are registered with the registration service (JSON file in the first step) upon deployment
- [x] Documentation on how to deploy and get started with the MVD
- [ ] Deployment can be performed based on step by step instructions without having deep technical expertise
- [x] A pipeline can be triggered to deploy the MVD components.
- [ ] 3 participants are in the MVD.

## Tasks
- [ ] Add instructions to deploy MVD components with 3 participants in a new Azure subscription.
- [x] Add instructions to destroy the deployment
- [ ] <strike>Add instructions to test the MVD.</strike> (Will not do because this would be part of the UI explanation)
- [x] Adapt CD to test this deployment if needed.
- [x] Create pipeline that can be triggered manually to deploy the components.
- [ ] Add 3 participants.
