### ISSUE TITLE
Dataspace Authority Self-Description

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#19]
Feature agera-edc/MinimumViableDataspace#36
After agera-edc/IdentityHub#11
After agera-edc/IdentityHub#21 

## Description

Provide a self-description document for the Dataspace Authority via its IdentityHub (see agera-edc/MinimumViableDataspace#36 and agera-edc/IdentityHub#11). 

The content of the self-description document is currently not consumed by any use cases and thus can be defined based on the examples that were created for the last [Gaia-X Hackathon](#37).

## Acceptance Criteria

- [ ]  Self-description for the Dataspace Authority can be retrieved from the IdentityHub of the Dataspace Authority

## Tasks

- [ ] Set up self-description document for the Dataspace Authority
- [ ] Expose self-description document via IdentityHub

**Comment by bscholtes1A** [comment]
https://github.com/agera-edc/MinimumViableDataspace/pull/276
