### ISSUE TITLE
Identity Hub - Artifact Publishing

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#191]
## Description

Identity Hub artefacts need to be published to a Maven repository so that they can be consumed by multiple clients (among them the MVD)

## Acceptance Criteria
- [ ] Define which Maven repository must be used
- [ ] Identity Hub jars are published to a Maven repository 
- [ ] MVD uses published dependencies instead of building the Identity Hub locally

## Tasks
