### ISSUE TITLE
Identity Hub - Read-Only implementation with Integration Tests

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#195]
Feature #122 
After #164

## Description

Initial Identity Hub implementation supporting the following DWN interfaces in the [IdentityHubClient implementation](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubClientImpl.java):

- [Collections Query](https://identity.foundation/decentralized-web-node/spec/#query) to query Verifiable Credentials
- [Feature Detection](https://identity.foundation/decentralized-web-node/spec/#feature-detection) listing all the aforementioned operations as supported.

Messages need to be processed by a pipeline following [the tech specificacion](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#request-processing):
- The RequestProcessingService will dispatch to an InterfaceMethodProcessor based on interface type ("CollectionsQuery", "FeatureDetection") of the incoming method field of of each message in the request (requests contain an array of message objects).

The Identity Hub needs to be implemented as an EDC extension to support the [collocated test deployment topology](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#ii-deployment-topologies)

An HTTP client similar to [IdentityHubClient](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubClientImpl.java) must be provided in an own extension as well for easier client integration.

Verifiable Credentials follow the model in [the spec](https://www.w3.org/TR/vc-data-model/).

No Authentication/Authorisation required for any endpoint.

## Acceptance Criteria
- [ ] Identity Hub is implemented as an EDC extension
- [ ] Identity Hub supports the read-only operations listed above
- [ ] Verifiable Credentials are implemented following the model in [the spec](https://www.w3.org/TR/vc-data-model/)
- [ ] Identity Hub architecture according to the specs listed above
- [ ] Identity Hub client is implemented
- [ ] A CredentialsVerifier is implemented in similar way as [here](https://github.com/microsoft/edc-showcase/blob/main/extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/did/credentials/IdentityHubCredentialsVerifier.java) to retrieve Verifiable Credentials in the [DecentralizedIdentityService](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java#L94)
- [ ] Identity Hub is covered by Integration Tests checking that mocked Verifiable Credentials (from a file or env var)  queried back using the CredentialsVerifier

## Tasks
