### ISSUE TITLE
MVD local machine setup for devs

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#20]
Feature #53 

## Description

Enable MVD to run on local developer computers of to enable efficient development and debugging of EDC connectors

## Acceptance Criteria

- [x] MVD components can be deployed to an own Azure Sub (KeyVaults, Storage Accounts, etc)
- [x] EDC connectors can be run on local machine
- [x] Instructions how to set up local development machine
- [x] Instructions how to debug EDC connectors 
- [ ] ~A Postman suite can be used to issue requests to EDC connectors~ moved to #159

## Tasks
- [x] Enable running system tests locally
- [x] Enable debugging
