### ISSUE TITLE
Identity Hub in-memory store

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#223]
# Description
We have a really simple implementation of the Identity Hub in-memory store.
This story is about improving the current implementation with thread safety, proper implementation + tests and EDC default mecanism.

## Acceptance criteria
- [ ] The store is thread safe
- [ ] The store have a proper implementation and tests
- [ ] The in-memory store if the default IdentityHubStore implementation (default extension)

## Tasks
- [ ] Make the store thread safe
- [ ] Add proper implementation and proper tests
- [ ] Make the IdentityHubInMemoryExtension the default extension with the @Provider(isDefault = true) annotation.
