### ISSUE TITLE
EDC Version Update to Milestone 5 Release

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#224]
## Description

The EDC needs to be updated to the [MS 5 Release](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/milestone/6). 

The Milestone 5 release is the latest _stable_ release and should be the EDC version to be used for the MVD until a next stable release is available (the MVD can then be used as an additional means to test the EDC release).

_Note: if the MS 5 does not work as expected, i.e. in case of bugs, the MS 5 version should be patched instead of updating the EDC version for the MVD to the latest version of the EDC._

## Acceptance Criteria

- [ ] EDC version for the MVD is updated to the MS 5 release
- [ ] MVD works as expected after updating the EDC version

## Tasks

- [ ] Review changes on EDC to identify breaking changes for the MVD
- [ ] Update EDC version and create deployment
- [ ] Perform a manual MVD test vie the DataDashboard

**Comment by algattik** [comment]
First step: https://github.com/eclipse-dataspaceconnector/DataDashboard/pull/6/files
