### ISSUE TITLE
Registration service: integrate policy engine

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#225]
Feature #24

## Description

For #11 we apply policies on participant verifiable credentials. As a first step toward this, we want to integrate a policy engine to derisk this item.

## Acceptance Criteria

- [x] Registration service apply membership policy - based on fixed inputs.
- [x] Test coverage.

## Tasks
- [x] Define a sample hardcoded policy and input data (so that the policy evaluation result is always succeeding).
- [x] Implement EDC policy engine in Registration Service, to apply policy on input data and use the result to admit a participant (in enrollment request).

**Comment by paullatzelsperger** [comment]
The idea is to obtain a prospective participant's DID, extract the claims and verify them against an "onboarding policy". Both the DID and the Policy can be faked, it is more about figuring out and verifying that the policy engine does indeed work in this situation.
