### ISSUE TITLE
IdentityHub spec implementation

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#225]
# Description

In the IdentityHub, there are certain aspect of the model [spec](https://identity.foundation/decentralized-web-node/spec/) that we didn't implemented yet.
The rules that have not been implemented yet have been added as TODOs in the IdentityHub repository.
For each TODO, we should figure out if the spec should be implemented and implement it if needed

# Acceptance criteria
- [ ] For each spec, decide if it should be implemented or not
- [ ] Validation is done for needed specs

# Tasks
- [ ] Add validation for specs
- [ ] Add tests for the validation
