### ISSUE TITLE
IdentityHub Client and CredentialsVerifier

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#228]
Feature #122 

## Description

An HTTP client similar to [IdentityHubClient](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubClientImpl.java) must be provided in an own extension as well for easier client integration.

A CredentialsVerifier is implemented in similar way as [here](https://github.com/microsoft/edc-showcase/blob/main/extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/did/credentials/IdentityHubCredentialsVerifier.java) to retrieve Verifiable Credentials in the [DecentralizedIdentityService](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java#L94)

## Acceptance Criteria
- [ ] Implement Identity Hub HTTP Client
- [ ] Implement Credentials Verifier
- [ ] Adapt integration tests to use Credentials Verifier to read credentials

## Tasks
