### ISSUE TITLE
Initial CI/CD Setup

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#24]
## Description 

Deploy initial EDC setup. The runtime only contains the Data Management API surface with no customisations and no data.

Scope is summarised below, see document for more details.

Core infrastructure. GitHub action to deploy:
-	Azure subscription
-	Azure AD application for use by GitHub project
-	Azure AD application for use by EDC to connect to Azure Key Vault
-	Base infrastructure (ACR, Tfstate)

CD: initial scope
-	Build and push to ACR
-	Deploy dataspace participant job matrix
-	Job for destroying infrastructure

## Tasks

- [x] Develop and document idempotent manual github actions to create Azure AD application for GitHub federated credential
- [x] Develop and document idempotent manual github action to configure Azure AD application and service principal and secret to connect to AKV, and upload the credential as a GitHub secret
- [x] Develop and document idempotent manual github action to deploy ACR and Terraform state storage account (use Azure CLI, not Terraform).
- [x] Develop CI/ CD pipeline with build job, deploy job matrix, and destroy job.
- [x] Document CD pipeline.

## Acceptance criteria

- [x] A developer can spin the system in their own fork with clear instructions.
- [x] Steps for the above are clearly documented.
- [x] CD job tests that EDC application is healthy.
- [x] Destroy job destroys all infra even on partial deployment/health test failures.
- [x] Branches do not interfere with each other: resources can be deployed in parallel (e.g. using GitHub run_id in resource names), if not possible then concurrency is limited

## Stories

- [x] #25
- [x] #26
