### ISSUE TITLE
Application insights integration for Registration Service deployment

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#247]
##  Description

OpenTelemetry-based observability is required for the MVD as it is currently in place for the EDC, to allow developers to investigate issues more effectively. This includes distributed tracing across applications, logging and metrics. Data shall be collected in Azure Monitor.

At this time we deploy a single Azure Monitor instance for all participants.

Changes required: OpenTelemetry agent in runtime, injecting key into Registration Service runtime. Using EDC `jdk-logger` module for proper traces integration. Propagate `TraceContext` across enrollment state machine.

See https://github.com/agera-edc/MinimumViableDataspace/pull/237/files for a template (how this was done for the EDC)

## Acceptance Criteria
- [x] MVD distributed traces, logs and metrics for RS are visible in Azure Monitor
- [x] traces correlate with EDC runtimes
- [x] trace spans state machine process from initiation to completion
 
## Tasks
- [x] Set up agent and environment variables in RS container for App Insights integration
- [x] Use `Telemetry` class trace context utils to propagate context across state machine
