### ISSUE TITLE
[Spike] GAIA-X June Hackathon Preparation: publish SDD

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#25]
Feature agera-edc/MinimumViableDataspaceFork#37 

## Description

To be GAIA-X compliant every participant of dataspace and dataspace authority needs to have a GAIA-X compliant self-description document. This self-description document must be verifiable using /verify or /verify/raw apis at https://compliance.gaia-x.eu/api/#/  

As registration service initial development is a work in progress so to begin with self-description document can be added for participants only and verification process remain manual as a first step.

## Acceptance Criteria

- [ ] Create SDD which can be verified on https://compliance.gaia-x.eu/api/#/  e..g. /verify/raw
- [ ] Every dataspace participant has a GAIA-X compliant SDD available on well-known endpoint.
- [ ] Dataspace authority has a a GAIA-X compliant SDD available on well-known endpoint.
- [ ] Update docs
- [ ] Code is available in a spike branch (not merged into main branch)

## Tasks

Same as acceptance crtieria.

**Comment by algattik** [comment]
https://compliance.gaia-x.eu/docs/
