### ISSUE TITLE
RegistrationService - code quality tools

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#253]
## Description

For better developer's awareness on the code quality we would like to enable the code quality tools (Checkstyle, CodeQL) in RegistrationService repository the same way they are used in EDC repository. Checkstyle and CodeQL should run as a part of CI workflow. 
Checkstyle is currently enabled for PRs in the same repository but not from downstream forks to upstream repo.

## Acceptance Criteria

- [ ] Code quality tools report potential issues in the PRs (both from forks and downstream PRs) 
- [ ]  Usage of the tools is documented both for local development and CI

## Tasks

- [ ] make sure Checkstyle check is enabled for PRs in both downstream forks and upstream repos
- [ ] add CodeQL workflow and enable it for PRs
- [ ] documentation
