### ISSUE TITLE
IdentityHub - code quality tools

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#254]
## Description

For better developer's awareness on the code quality we would like to enable the code quality tools (Checkstyle, CodeQL) in IdentityHub repository the same way they are used in EDC repository. Checkstyle and CodeQL should run as a part of CI workflow. 

Checkstyle is currently enabled for PRs in the same repository but not from downstream forks to upstream repo.

## Acceptance Criteria

- [x] Code quality tools report potential issues in the PR 
- [ ]  Usage of the tools is documented both for local development and CI

## Tasks

- [x] make sure Checkstyle check is enabled for PRs both downstream forks and upstream repo
- [x] add CodeQL workflow and enable it for PRs
- [x] documentation
