### ISSUE TITLE
Bug: CI checks fail on main

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#258]
# Description
When merging on main, CI is triggered. It looks like it fails:
See the CI checks on commits:

https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/commits/main

It seems to be related to a resource being created during CI that already exists.

Acceptance criteria
- [] CI checks are green when merging to main

# Tasks
- [] Investigate the bug
- [] Fix the bug
