### ISSUE TITLE
Upgrade RegistrationService version in MVD

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/MinimumViableDataspace#266]
## Description
MVD is not compatible with the latest Registration Service changes.
 
## Acceptance Criteria

- [x] MVD is using the latest RS version
 
## Tasks
- [x] Update MVD with the latest Registration Service version
- [x] Fix issues in MVD
