### ISSUE TITLE
Update MVD Local Deployment documentation

### ISSUE THREAD

**Issue by chrislomonico** [agera-edc/MinimumViableDataspace#273]
Feature #91 

## Description

MVD local deployment doc (`system-tests/README.md`) needs to be updated to reflect the usage of the EDC `v0.0.1-milestone-5` release.  Currently the documentation is referencing a commit hash.

## Acceptance Criteria

- [ ] documentation is updated
- [ ] documented process can be followed and lead to a successful local deployment

## Tasks

- [ ] update `system-tests/README.md` to provide clear instructions on local build/deploy
