### ISSUE TITLE
Web DID: connector authentication in IDS calls

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#35]
Feature #28 
After #5 

## Description

With the certificate available in KeyVault and the identity document ready it is now possible to enable Web DID authentication for IDS calls:
- The connector needs to be configured properly with the corresponding KeyVault and WebDID identity document:
  - edc.vault.name
  - edc.identity.did.url
- The extension `identity-did-service` containing `DecentralizedIdentityService` must be used in the connector deployment.
- Use a dummy implementation to simulate "region->eu" credential

## Acceptance criteria
- [x] Web DID authentication working properly
- [x] Integration test verifies that authentication is working

## Tasks
- [x] Add above mentioned extensions to the EDC connector
- [x] Configure properties in the EDC connector
- [x] Integration test checking JWTs are verified on IDS requests
- [ ] ~If possible write an integration tests to check failed JWT verifications~
