### ISSUE TITLE
CPR OneWeek demo

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#38]
## Description
Prepare the demo showing the work done during OneWeek: the integration of Dataverse with EDC.
Show publishing of an asset + transfer from Dataverse to blob storage.

## Acceptance criteria
- [x] Recording is ready
- [x] Demo shows asset publication and transfer from Dataverse to blob

## Tasks
- [x] Integrate together the publishing of asset and the transfer
  - [x] Add the Dataverse URL in asset properties & and uses this property for the data transfer.
- [ ] Get the app token programmatically instead of hardcoding it
- [x] Record the demo
