### ISSUE TITLE
Registration Service - Command line client - Update to use Dataspace Authority DID to get enrollment endpoint.

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#43]
Feature #58
After #45 

## Description

Command line client needs to read registration service enrollment api endpoint from Dataspace authority DID document.

## Acceptance Criteria 
- [x] Registry service enrollment api endpoint available in DID document.
- [x] Update command line client to read enrollment api endpoint from Dataspace authority DID document.
- [ ] Update command line client to remove endpoint URL parameter.

## Tasks
Same as acceptance criteria.
