### ISSUE TITLE
Registration Service - rest api endpoint to fetch onboarding status 

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#46]
Feature agera-edc/MinimumViableDataspace#177
After agera-edc/MinimumViableDataspace#186 agera-edc/MinimumViableDataspace#182 
After #14

## Description

Registry service needs to expose rest endpoint to show current status of an onboarding request. API response should not map internal states one to one on output as this may leak some internal sensitive information.

(Possible internal states for state machine are implemented under agera-edc/MinimumViableDataspace#182)

## Acceptance Criteria

- [x] Update ADR of agera-edc/MinimumViableDataspace#186 (if needed)
- [x] Endpoint to get current state of the onboarding is available on Registry service.
- [x] Open API doc is generated/updated and validated during CI build.
- [x] Avoid mapping internal states on api output one to one. API should be more meaningful from user perspective.
- [x] Test coverage
- [x] Onboarding status can be retrieved based on the DID, i.e. an applicant can only retrieve it's own onboarding status
- [ ] <strike>Registration CLI utilize this endpoint with busy polling during deployment workflow to get the onboarding status.</strike>
- [ ] MVD Deployment to use this new endpoint (using cli client) to fetch onboarding status

(API response can be IN_PROGRESS, APPROVED, DECLINED) 

## Tasks

- [x] Update ADR with details of status endpoint.
- [x] Create endpoint to get status of onboarding given an identifier.
- [x] UTs/ITs to cover implementation.
- [x] System test to cover participant onboarding flow using registry service onboarding + status endpoint.
- [x] Generate OpenAPI docs.
- [ ] Update MVD deployment to use this new endpoint (using cli client) to fetch onboarding status.

**Comment by cpeeyush** [comment]
Registration service cli will not do the busy polling to get status of the onboarding participant as it is possible that registration take longer time to be approved (for example in a case where a manual approval is needed from external authority).

**Comment by cpeeyush** [comment]
DTO Responses are:

-  ONBOARDING_IN_PROGRESS, // participant onboarding in progress
-  ONBOARDED, // participant is fully onboarded
-  DENIED, // participant onboarding request denied
