### ISSUE TITLE
Registration Service - Enrollment endpoint State machine

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#47]
Feature agera-edc/MinimumViableDataspace#177
After agera-edc/MinimumViableDataspace#186 

## Description

Registration service enrollment endpoint does onboard new participant asynchronously and during this processing a participant goes through different states. To transition between these states a state machine needs to be introduced. Initial proposal of different states is on specs https://github.com/Metaform/mvd/blob/main/registration-service/registration-service-tech-spec.md#3-participant-record.

State machine library from EDC :common:state-machine-lib should be used.

Interaction with other service e.g. identity service/policy can be stubbed for now e.g. always return true.

## Acceptance Criteria

- [x] The state machine logic is documented in decision record log
- [x] Registration service enrollment endpoint uses simple state machine logic.
- [x] Open API doc is generated/updated and validated during CI build.
- [x] Interaction with non-implemented service stubbed for future extensions.

## Tasks

- [x] Update ADR of task agera-edc/MinimumViableDataspace#186 (if needed).
- [x] Implement logic for registration service enrollment state machine implemented with given states as per spec (Interaction with non-implemented service should be stubbed for future extensions). Use in-memory store to save states.
- [x] Generate/update and validate Open API doc during CI build.
- [x] Test coverage.
