### ISSUE TITLE
Deployment from Forked Repository

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#47]
Feature #1 

## Description

As a developer using the MVD, I want to fork the MVD repository and deploy my own MVD instance without running into resource name conflicts.

Resource name conflicts can happen for resources with globally unique names if multiple instances of the MVD are deployed via CD workflows.

Currently, each resource has a prefix name, which is the GitHub run ID. Two repositories may have the same run ID.
This can cause resource name conflicts.

_Note: A possibility to fix this problem is to let the fork repo user to choose a static prefix._

## Acceptance criteria

- [x] MVD CD can run from 2 fork repos that use the same Git run ID without resource name conflicts.

## Tasks
- [x] Add a default resource prefix.
- [x] Explain in documentation how to update this prefix.
