### ISSUE TITLE
Registration Service - rest api endpoint to enroll/Onboard a dataspace participant asynchronously

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#48]
Feature agera-edc/MinimumViableDataspace#177
After agera-edc/MinimumViableDataspace#181 

## Description
Registration service should expose an endpoint to enroll a new participant. This endpoint should do the work for enrollment asynchronously. Currently a shared file is used to maintain list of participants, but with this work registration should move to use an in-memory store to maintain this list and do not use shared file anymore.

## Acceptance Criteria
- [ ] ~The approach is documented in the decision record doc.~ in agera-edc/MinimumViableDataspaceFork#20 
- [x] Enrollment of a participant can be performed by calling a registry service REST API endpoint.
- [x] Open API doc is generated/updated and validated during CI build.
- [x] Registration service uses in-memory store to maintain list of participant and not shared file.

## Tasks

- [ ] ADR about enrollment endpoint if required. (#209)
- [x] Add Rest endpoint to enroll new participant is available for registration service. This endpoint should use an in-memory store to keep list of participant. Enrollment should be done asynchronously.
- [x] Generate/update and validate Open API doc during CI build.
- [x] Add UTs/ITs to cover endpoint implementation.
- [ ] Update MVD deployment to use this new endpoint in-order to enroll dataspace participant.
- [ ] Update MVD deployment and initial setup to remove creation of shared participant list file.
