### ISSUE TITLE
Web DID: create identity document

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#5]
Feature #28 
After #34 

## Description
Every dataspace participant needs to create a JSON document, which represents their DID containing the following items:
- the participant's public key

An example of such a document (the name of the participant here is "consumer"): 
```json
{
  "id": "did:web:edcshowcasegpstorage.z6.web.core.windows.net:consumer",
  "@context": [
    "https://www.w3.org/ns/did/v1",
    {
      "@base": "did:web:edcshowcasegpstorage.z6.web.core.windows.net:consumer"
    }
  ],
  "verificationMethod": [
    {
      "id": "#consumer-key-1",
      "controller": "",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "4mi45pgE5iPdhluNpmtnAFztWi8vxMrDSoXqD5ah2Rk",
        "y": "FdxTvkrkYtmxPgdmFpxRzZSVvcVUEksSzr1cH_kT58w"
      }
    }
  ],
  "authentication": [
    "#consumer-key-1"
  ]
}
```

That means, that a public/private key pair must be generated beforehand and offline. 
Furthermore, the URL of the DID document must be known before and templated it at deployment.

The URL to this document will then also be a part of the connector's self description and must be supplied during onboarding (#7).

#### Preconditions
- Public/Private key pair is available
- a publicly available location (AzureStorage, S3 bucket, Cloudflare CDN,...) to host the DID is available and it's public URL is known

## Acceptance Criteria

- [ ] An identity document can be generated, e.g. using a JSON template
- [ ] The Identity document can be deployed using Terraform
- [ ] The Identity document is publicly available upon deployment using the `did:web` key
- [ ] An integration test verifies the Identity documents after deployment automatically

## Tasks

- [ ] Adapt Terraform code to deploy a static web app endpoint
- [ ] Adapt Terraform code to generate JSON DID document and store it in the web app endpoint
