### ISSUE TITLE
CD: Remote backend for terraform state

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#51]
# Description
Github artifacts where the terraform state is stored does not get deleted. Artifact contains secret information. So we will use common remote backend storage to keep this state.

_Originally posted by @cpeeyush in https://github.com/agera-edc/MinimumViableDataspace/pull/50#discussion_r850443585_

# Acceptance criteria
- [ ] CD uses a remote backend.

# Tasks
- [ ] Add remote backend to terraform
- [ ] Make sure CD does not publish state in artifact
