### ISSUE TITLE
MVD - Repository Setup

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#54]
Feature agera-edc/MinimumViableDataspaceFork#62
After agera-edc/MinimumViableDataspaceFork#35 agera-edc/MinimumViableDataspaceFork#33

## Description

Create a new MVD repository repository in the [eclipse-dataspaceconnector org](https://github.com/eclipse-dataspaceconnector) and move the content of the [agera MVD repository](https://github.com/agera-edc/MinimumViableDataspace) to this new repository.
Paul requested the creation of the repository and it will be created by Markus Spiekermann. The repositories can't be created by agera team members.

For initial development, we will track issues in the downstream repositories only, work on a `dev` branch and merge back to upstream in batches. This allows us to work flexibly in our fork (without requiring committer status in the `eclipse-dataspaceconnector` org). 
## Acceptance Criteria

- [x] Repository is available in the eclipse-dataspaceconnector organization
- [x] All Agera team members have access to push into the repo
- [x] Issues in the agera-edc GitHub org related to the Identity Hub are moved to the downstream Repository

## Tasks

- [x] Repository is created in eclipse org
- [x] Repository downstream fork is created in agera org
- [x] Set up License terms in the README
- [x] Double check that the correct protections rules are in place for the `main` branch
- [ ] Document process to contribute in the README (Code of conduct, sign the ECA etc.)
~- [ ] Document internal agera process to contribute in our wiki~ obsolete: already documented
- [x] Set license to Apache 2.0
- [x] Stories are moved to fork in agera org

## Acceptance criteria
- [x] A new MVD repository is created in the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector) org
- [x] Content of the [agera MVD repository](https://github.com/agera-edc/MinimumViableDataspace) is migrated to the [eclipse-dataspaceconnector MVD repository](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace)
- [x] License terms are set up in the README
- [ ] Process on how to contribute is documented (Code of conduct, sign ECA etc, for the example see [CONTRIBUTING.md](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md) from EDC)
- [ ] Internal Agera process to contribute to the MVD is documented in our internal wiki
- [ ] `main` branch protection rules are in place (`main` can only be updated by having a contributor merging a PR)
- [x] <strike>`dev`</strike> `main` branch protection rules in the downstream repo are in place
<strike>- [ ] The downstream target branch is `dev`</strike> 

## Tasks
- [x] Migrate content of [agera-edc/MinimumViableDataspace repository](https://github.com/agera-edc/MinimumViableDataspace) to the new one
- [x] Set up License terms in the README
- [ ] Document process to contribute in the README (Code of conduct, sign the ECA etc.)
- [ ] Double check that the correct protections rules are in place for the `main` branch
~- [x] Add `dev` branch protection rules in the downstream repo~ (Obsolete)
~- [ ] Document internal agera process to contribute to the MVD in our wiki~ (Obsolete)
~- [ ] Update the downstream target branch to be `dev`
