### ISSUE TITLE
EDCDataDashboard - Repository Setup

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#55]
Feature agera-edc/MinimumViableDataspaceFork#62
After agera-edc/MinimumViableDataspaceFork#34

## Description
Create a new EDCDataDashboard repository in the [eclipse-dataspaceconnector org](https://github.com/eclipse-dataspaceconnector) and move the content of the [agera-edc/EDCDataDashboard repository](https://github.com/agera-edc/EDCDataDashboard) to this new repository.
Paul requested the creation of the repository and it will be created by Markus Spiekermann. The repositories can't be created by agera team members.

For initial development, we will track issues in the downstream repositories only, work on a `dev` branch and merge back to upstream in batches. This allows us to work flexibly in our fork (without requiring committer status in the `eclipse-dataspaceconnector` org). 

## Acceptance Criteria

- [x] Repository is available in the eclipse-dataspaceconnector organization
- [x] All Agera team members have access to push into the repo
- [x] Issues in the agera-edc GitHub org related to the Identity Hub are moved to the downstream Repository

## Tasks

- [x] Repository is created in eclipse org
- [x] Repository downstream fork is created in agera org
- [x] Set up License terms in the README
- [x] Double check that the correct protections rules are in place for the `main` branch
- [x] Document process to contribute in the README (Code of conduct, sign the ECA etc.)
~- [ ] Document internal agera process to contribute in our wiki~ obsolete: already documented
- [x] Set license to Apache 2.0
- [x] Stories are moved to fork in agera org

## Notes
To avoid complexity it has been decided that the same flow for all repos will be applied and followed; anything in the agera-org will be downstream of the upstream repository in the `eclipse-dataspaceconnector` org
