### ISSUE TITLE
MVD CI/CD setup

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#56]
Feature agera-edc/MinimumViableDataspaceFork#62 
After agera-edc/MinimumViableDataspaceFork#54

## Description
Setup CI/CD of the new [MVD repository](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace) in the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector) org.

Jim and Paul will take care of this setup, but this story is a placeholder to keep track of the state, and in case support from team members is needed.

## Acceptance criteria
- [x] Azure subscription needed for CI/CD is setup
- [x] Actions secrets needed for CI/CD are configured in the github repository
- [x] CD_RESOURCES_PREFIX is configured in CD workflow
- [x] Deploy & Destroy workflow work

## Tasks
- [x] Initiate the work & coordinate with Jim & Paul
- [x] Verify that CI/CD works
- [x] Support Jim & Paul if needed
- [x] Setup CI/CD of forked repository

**Comment by ouphi** [comment]
Assigning @algattik  to setup CI/CD of workflow of the [forked repository](https://github.com/agera-edc/MinimumViableDataspaceFork)

**Comment by cpeeyush** [comment]
PR for upstream. As a temporary step skipping Azure deployment from downstream forks.
https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/pull/17

See PR for further details.

**Comment by cpeeyush** [comment]
To update FsVault in order to add Parsers support https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1658
