### ISSUE TITLE
Policy: Spike

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#57]
Feature #3 

## Description

As a dataspace participant I want to have my policies enforced to ensure that my assets are only used for the intended purpose.

This story is for spiking on the components needed to implement only a simple, static rule, that the caller identity has a claim "region=eu"

## Acceptance Criteria

- [x] Follow up issues are created to allow implementing the scenario (see story #64 )
- [x] The follow up issues, when implemented, would have a scenario automatically tested such as: one provider, one consumer with region=eu and one consumer with region=us. An asset negotiation with one consumer fails, with the other it succeeds

## Tasks

- [x] Evaluate code provided by Ben: CatalogDataseedingExtension.java ,AbsSpatialPositionConstraintFunction.java https://github.com/bscholtes1A/edc-showcase/tree/edc-sandbox-1a/extensions/dataseeding/controlplane/src/main/java/org/eclipse/dataspaceconnector/dataseeding/connector
edc-showcase/extensions/dataseeding/controlplane/src/main/java/org/eclipse/dataspaceconnector/dataseeding/connector at edc-sandbox-1a 
- [x] Create follow-up stories to cover policies for #64

**Comment by algattik** [comment]
Created follow-up story #100
