### ISSUE TITLE
Add Asset - Azure Storage

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#6]
Feature #3 

after https://github.com/agera-edc/EDCDataDashboard/issues/15

## Description

As a dataspace participant I want to add a new asset in order to share it with other participants in a subsequent step.

This action refers to creating an `Asset` and a `DataAddress` (pointing to the physical location of the data item) in the participant's connector. At this time, other dataspace participants do _not yet_ have access to the Asset, because no `ContractDefinition` exists yet (#9).

The following steps are necessary:
1. generate a `DataAddress` containing relevant information (bucket name, account name, etc.)
1. generate an `Asset` object describing the data item
1. call REST endpoint to insert the `Asset`/`DataAddress` tuple into the connector at `POST /assets`

In the first iteration of the MVD, composing the `Asset`/`DataAddress` is done through and aided by the connector's web UI using a simple text entry widget. So when the user selects `AzureStorage` the widget should only display input for those particular properties (Account, container, etc.).

Initially, we'll support the data address types `AzureStorage` and `api` (#93) with the following properties:
- type=AzureStorage: account name, container name
- `type=api`: URL

<strike>_Note: Testing for `AmazonS3` is out of scope for this story and should be shown as not supported_</strike>

_Note: The blob container to be added needs to exist prior to adding the asset._

Frontend work: agera-edc/EDCDataDashboard#15

## Acceptance Criteria

- [x] A web UI provides an easy and guided way to create `DataAddress` and `Asset` objects. See  agera-edc/EDCDataDashboard#15.
- [ ] <strike>`DataAddress` and `Asset` objects can be uploaded to EDC via its REST API</strike> (Not verified as part of this story but it is working as for system test Asset are getting creating using DataManagment APIs.)
- [x] Documentation on how to upload new assets through the UI <strike>and REST API</strike> is available
- [x] Assets can be uploaded based on step by step instructions without having deep technical expertise
- [ ] <strike>`AmazonS3` is shown as not supported</strike>

## Tasks

- [x] Add/update instructions in docs

**Comment by cpeeyush** [comment]
Should we move AmazonS3 out of scope for this story as we cannot test it ?

**Comment by cpeeyush** [comment]
Current UI only show Azure Storage, so S3 is out of scope.
