### ISSUE TITLE
MVD & EDCDataDashboard Repositories Migration

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#62]
## Description

The current MVD repository as well as the EDCDataDashboard repository reside in the `agera-edc` org. We now want to make the MVD available to other parties and put the source code under governance of the Eclipse project. 

Both repositories should therefore be moved to the `eclipse-dataspaceconnector` org, once we have a stable version where the basic scenarios are supported.

For initial development, we will track issues in the downstream repositories only, work on a `dev` branch and merge back to upstream in batches. This allows us to work flexibly in our fork (without requiring committer status in the `eclipse-dataspaceconnector` org). 

## Acceptance Criteria

- [x] Repository for the MVD is set up in the `eclipse-dataspaceconnector` org
- [x] Repository for the EDCDataDashboard is set up in the `eclipse-dataspaceconnector` org
- [x] Forks in the `agera-edc` org for the two repositories use the same process as for the `DataSpaceConnector` repository
- [x] CI/CD is in place for both upstream and downstream repositories
- [x] Process on how to merge to `main` is defined
- [x] `README` files for both repositories are in place and license terms are set up

## Stories
- [x] agera-edc/MinimumViableDataspaceFork#35 
- [x] agera-edc/MinimumViableDataspaceFork#34 
- [x] agera-edc/MinimumViableDataspaceFork#55
- [x] agera-edc/MinimumViableDataspaceFork#54 
- [x] agera-edc/MinimumViableDataspaceFork#56
- [x] agera-edc/MinimumViableDataspaceFork#53
