### ISSUE TITLE
Web DID: IdentityHub and verifiable credentials

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#64]
Feature #28 
After #57 
After #35

## Description
[Verifiable credentials](https://www.w3.org/TR/vc-data-model/#credentials) are tamper-proof credentials that can be verified cryptographically. A [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) is a set of one or more [claims](https://www.w3.org/TR/vc-data-model/#dfn-claims) made by the same [entity](https://www.w3.org/TR/vc-data-model/#dfn-entities) (in our case the dataspace participant). The IdentityHub is the component that delivers verifiable credentials for a dataspace participant. In the MVD, each participant has an own IdentityHub where its verifiable credentials are stored. These credentials can be seed through an endpoint available as well in the IdentityHub for this purpose.

In this story, verifiable credentials will not be cryptographically secured (credentials won't be signed by a central authority or any other participant). Thus, the IdentityHub of each participant merely provides credentials as a key-value map without any cryptographic signature.

## Tasks
- [ ] Verifiable credential are retrieved from the corresponding participant's IdentityHub
- [ ] A sample verifiable credential (region=eu) is used to restrict access for some participants not in the eu region

## Tasks
- [ ] Seed sample identity hub credential using Postman collection and automating seeding in deployment using newman
  - Make sure `identity-did-core` extension is being used
  - Use endpoint '/identity-hub/collections' (see [IdentityHubController](https://github.com/agera-edc/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubApiController.java#L56))
  - Seed same data as in the [edc-showcase](https://github.com/microsoft/edc-showcase/blob/main/extensions/dataseeding/hub/src/main/java/org/eclipse/dataspaceconnector/dataseeding/catalog/IdentityHubDataseedingExtension.java#L25) (region->eu)
- [ ] Implement [IdentityHubVerifier](https://github.com/microsoft/edc-showcase/blob/main/extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/did/credentials/IdentityHubCredentialsVerifier.java) that connects to the IdentityHub to retrieve verifiable credentials
- [ ] Open a upstream PR to move the IdentityHubVerifier to EDC core: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1070
- [ ] Coordinate work with #100 so that a policy to restrict usage to participants in the EU region can be implemented in #100

**Comment by zeier** [comment]
Closing this story as it is outdated due to the latest conversations.
