### ISSUE TITLE
UI Design for Join Dataspace

### ISSUE THREAD

**Issue by JankaKoen** [agera-edc/MinimumViableDataspace#65]
## Description
This is a task to plan the UI for the MVD in Figma for Joining a Dataspace

## Tasks
- [ ] Add the option to cancel or save the request for later
- [ ] Copy Membership policies to all screens 
- [x] Add Notifications
- [x] Adjust Text in Stepper
- [x] Create Component for Stepper
- [ ] Adjust Screen for pasting DID

**Comment by zeier** [comment]
HX items will be tracked elsewhere.
