### ISSUE TITLE
UI deployment

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#65]
After #19 #18

# Description
Add UI deployment with Terraform.
Might need to be refined after #18 and after #19

# Acceptance criteria
- [ ] UI can be deployed with other MVD components
- [ ] ~Steps to deploy and access the UI are documented~ (will be done in #19, since currently the build destroys the environment right away)
- [ ] UI is deployed in CD to test the terraform
- [ ] The UI can be used and can call the backend

# Tasks
- [ ] ~Build and push image to ACR in build~ (will be done in https://github.com/agera-edc/EDCDataDashboard/issues/1)
- [ ] Add UI deployment to Terraform
- [ ] ~Document steps to deploy the UI~
- [ ] Set up CORS
- [ ] Set backend URL
