### ISSUE TITLE
Add Policy

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#8]
Feature #3

## Description

As a dataspace participant I want to formulate and add new policies so that I can apply them to my data offerings.

The connector's web UI offers a widget to insert a policy and upload it to the connector's REST API using the `POST /policies` endpoint.

As a simplification, this can just be a multiline textbox where users need to paste a JSON string. We don't need a complicated policy editor/wizard for now.

_Note: front end work is done in agera-edc/EDCDataDashboard#8

## Acceptance Criteria

- [x] Web UI provides a way to add new policies
- [x] A subsequent call to `GET /policies` should include the new item
- [x] Existing policies are visible on the UI
- [x] Documentation on how to create and upload policies is available
  - [x] Documentation includes examples of policies supported by the MVD
- [x] Policies can be added based on step by step instructions without having deep technical expertise

## Tasks

- [x]  Add multiline textbox or text field (see if adding a UI component with form fields is easier) in UI where users can paste `POST /policies` request body JSON. (Part of UI story https://github.com/agera-edc/EDCDataDashboard/issues/8) 
- [x] Create new policy request can be submitted successfully from UI.
- [x] Add section in UI to show existing policies which can be retrieved using `GET /policies` endpoint. (Part of UI story https://github.com/agera-edc/EDCDataDashboard/issues/8) 
- [x] Document step by step instructions on how to create policies from UI and also add example of all supported policies in MVD currently.

**Comment by cpeeyush** [comment]
@zeier do we also want to add a section in UI to show existing policies ?

(Added a task)
- Add section in UI to show existing policies which can be retrieved using GET /policies endpoint.

**Comment by zeier** [comment]
@cpeeyush let's add a story for that to the `EDCDataDashboard` repository and coordinate with @paullatzelsperger.
