### ISSUE TITLE
View Participants

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#83]
Feature agera-edc/DataDashboardFork#17 

## Description

As a dataspace participant, I want to see who the other participants in a dataspace are, to find out with whom I can exchange data.

_Note: UI work is covered by agera-edc/EDCDataDashboard#18_

## Acceptance Criteria

- [ ] Participants page is available that lists all participants per dataspace
- [ ] Documentation is available

## Tasks

- [ ] Add documentation for the Participants page

**Comment by zeier** [comment]
Participants can be retrieved from the Registration Service once it is implemented. This functionality is not required for the Data Dashboard (which is a UI for the DataManagementAPI) and will be implemented on the MVD UI.
