### ISSUE TITLE
Publish Asset (Contract Definition)

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#9]
Feature #3
Depends on https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1230 

## Description

As a dataspace participant I want to make my asset available to other participants so that they can view which assets are available to them.

The act of publishing an asset refers to the creation of a `ContractDefintion`, or to the addition of the asset to an existing `ContractDefinition`.

Consequently, the connector's web UI should offer a way to create a new `ContractDefinition`.
_Note: updating existing contract definitions is not possible for now, as the API does now expose this functionality._

Frontend work: https://github.com/agera-edc/EDCDataDashboard/issues/16

#### Preconditions
- `Asset` is already uploaded to EDC
- `Policy` is already uploaded to EDC

## Acceptance Criteria
- [x] New `ContractDefinition` objects can be created using the web UI. See https://github.com/agera-edc/EDCDataDashboard/issues/16
- [x] A subsequent request to `get /contractdefinitions` lists the newly created object.
- [x] The published asset is visible in other participant's catalog
- [x] Catalogs of other participants are refreshed when an asset is published
- [x] Documentation on how to publish assets through the UI is available
- [x] Assets can be published based on step by step instructions without having deep technical expertise

## Tasks

- [x] Make sure the UI (Contract Definition Editor tab) works with current Contract Definition API
- [x] Add/update instructions in doc

**Comment by cpeeyush** [comment]
PR: https://github.com/agera-edc/MinimumViableDataspace/pull/116
